'''版本号'''
__version__ = '0.3.9'
'''作者'''
__author__ = 'Charles'
'''标题'''
__title__ = 'DecryptLogin'
'''描述'''
__description__ = 'DecryptLogin: APIs for loginning some websites by using requests.'
'''链接'''
__url__ = 'https://github.com/CharlesPikachu/DecryptLogin'
'''邮件'''
__email__ = 'charlesblwx@gmail.com'
'''license'''
__license__ = 'Apache License 2.0'
'''copyright'''
__copyright__ = 'Copyright 2021-2022 Zhenchao Jin'