'''版本号'''
__version__ = '0.2.3'
'''作者'''
__author__ = 'Charles'
'''标题'''
__title__ = 'DecryptLogin'
'''描述'''
__description__ = 'Login some website using requests'
'''链接'''
__url__ = 'https://github.com/CharlesPikachu/DecryptLogin'
'''邮件'''
__email__ = 'charlesblwx@gmail.com'
'''license'''
__license__ = 'MIT License'